package marlin

// #cgo LDFLAGS: -lmarlin_zsk -L${SRCDIR}/../lib
// #include <stdbool.h>
// #include <stdlib.h>
// #include "./../lib/marlin_zsk.h"
import "C"
import (
	"encoding/hex"
	"log"
)

// ZebraLancerGenerateProofAndVerifyKey generates the zero-knowledge proof desribed by
// ICDCS paper ZebraLancer
func ZebraLancerGenerateProofAndVerifyKey(prefix, msg, sk, pk, cert, mpk, t1, t2 []byte) (proof Proof, verifyKey VerifyKey) {
	hexPrefix := C.CString(hex.EncodeToString(prefix))
	hexMsg := C.CString(hex.EncodeToString(msg))
	hexSk := C.CString(hex.EncodeToString(sk))
	hexPk := C.CString(hex.EncodeToString(pk))
	hexCert := C.CString(hex.EncodeToString(cert))
	hexMpk := C.CString(hex.EncodeToString(mpk))
	hexT1 := C.CString(hex.EncodeToString(t1))
	hexT2 := C.CString(hex.EncodeToString(t2))
	witness := C.ZebraLancerWitness{
		sk:   hexSk,
		pk:   hexPk,
		cert: hexCert,
	}
	proofAndKey := C.generate_proof_zebralancer(hexPrefix, hexMsg, hexMpk, hexT1, hexT2, witness)
	defer C.free_proof_and_verify(proofAndKey.proof, proofAndKey.vk)
	encodedProof, encodedVerifyKey := C.GoString(proofAndKey.proof), C.GoString(proofAndKey.vk)
	var err error
	if proof, err = hex.DecodeString(encodedProof); err != nil {
		log.Fatalln("Hex decode error")
	}
	if verifyKey, err = hex.DecodeString(encodedVerifyKey); err != nil {
		log.Fatalln("Hex decode error")
	}
	return proof, verifyKey
}

// ZebraLancerVerifyProof verifys the zero knowledge proof generated by requester with
// its public inputs
func ZebraLancerVerifyProof(t1, t2 []byte, proof Proof, verifyKey VerifyKey) bool {
	hexT1, hexT2 := C.CString(hex.EncodeToString(t1)), C.CString(hex.EncodeToString(t2))
	proofHex, verifyKeyHex := C.CString(hex.EncodeToString(proof)), C.CString(hex.EncodeToString(verifyKey))
	return bool(C.verify_proof_zebralancer(hexT1, hexT2, proofHex, verifyKeyHex))
}
